### ISSUE TITLE
Add support for filters or JQL

### ISSUE THREAD

**Issue by mbuck-r7** [flowdock/flowdock-jira-plugin#5]
One feature that this integration is lacking (vs. the Slack version of the JIRA integration) is the ability to only listen to events on issues in a particular filter. For a larger organization with multiple teams working on the same project, it's nice to be able to separate out the messages from a project that have a specific tag, for example. I see that [there's also a User Voice request](https://flowdock.uservoice.com/forums/36827-general/suggestions/2372001-add-filtering-to-jira-plugin) for this functionality. Thanks!

**Comment by RedBulli** [comment]
We just released an upgraded JIRA integration to Flowdock which supports JQL. https://www.flowdock.com/help/jira helps how to get started with the new integration.

This plugin will no longer be maintained.
